{##SHOWDATAFORCOLUMN}
{#IFDEF NOTDEFAULTTABLE}
{#IFDEF CANBENULL}
if ({#NOTDEFAULTTABLE} == null || (({#NOTDEFAULTTABLE}.Rows.Count > 0) && ({#NOTDEFAULTTABLE}[0].Is{#COLUMNNAME}Null())))
{
    {#SETNULLVALUE}
}
else
{
    if ({#NOTDEFAULTTABLE}.Rows.Count > 0)
    {
        {#SETCONTROLVALUE}
    }
}
{#ENDIF CANBENULL}
{#IFNDEF CANBENULL}
if ({#NOTDEFAULTTABLE} != null)
{
    {#SETCONTROLVALUE}
}
{#ENDIFN CANBENULL}
{#ENDIF NOTDEFAULTTABLE}
{#IFNDEF NOTDEFAULTTABLE}
{#IFDEF CANBENULL}
if ({#ROW}.Is{#COLUMNNAME}Null())
{
    {#SETNULLVALUE}
}
else
{
    {#SETCONTROLVALUE}
}
{#ENDIF CANBENULL}
{#IFNDEF CANBENULL}
{#SETCONTROLVALUE}
{#ENDIFN CANBENULL}
{#ENDIFN NOTDEFAULTTABLE}

{##GETDATAFORCOLUMNTHATCANBENULL}
{#IFDEF CANBENULL}
{#IFDEF NOTDEFAULTTABLE}
if (({#NOTDEFAULTTABLE} != null) && ({#NOTDEFAULTTABLE}.Rows.Count > 0))
{
    if ({#DETERMINECONTROLISNULL})
    {
        {#NOTDEFAULTTABLE}[0].Set{#COLUMNNAME}Null();
    }
    else
    {
        {#NOTDEFAULTTABLE}[0].{#COLUMNNAME} = {#CONTROLVALUE};
    }
}
{#ENDIF NOTDEFAULTTABLE}
{#IFNDEF NOTDEFAULTTABLE}
if ({#DETERMINECONTROLISNULL})
{
    {#ROW}.Set{#COLUMNNAME}Null();
}
else
{
    {#ROW}.{#COLUMNNAME} = {#CONTROLVALUE};
}
{#ENDIFN NOTDEFAULTTABLE}
{#ENDIF CANBENULL}
{#IFNDEF CANBENULL}
{#ROW}.{#COLUMNNAME} = {#CONTROLVALUE};
{#ENDIFN CANBENULL}