// Auto generated by nant generateGlue
// From a template at inc\template\src\ClientServerGlue\Connector.cs
//
// Do not modify this file manually!
//
{#GPLFILEHEADER}

//
// Contains the connector classes
//

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data;
using System.Threading;
using System.Runtime.Remoting;
using System.Security.Cryptography;
using Ict.Common;
using Ict.Common.Data;
using Ict.Common.Verification;
using Ict.Common.Remoting.Client;
using Ict.Common.Remoting.Shared;
using Ict.Common.Remoting.Server;
using Ict.Petra.Server.App.Core.Security;
using Ict.Petra.Shared;
{#USINGNAMESPACES}

namespace Ict.Petra.Server.M{#TOPLEVELMODULE}.Instantiator
{
    {#CONNECTORCLASSES}
}

{##CONNECTORCLASS}
/// <summary>
/// REMOTEABLE CLASS. Connector
/// </summary>
public class T{#NAMESPACE}Namespace : TConfigurableMBRObject, I{#NAMESPACE}Namespace
{
    /// <summary>Constructor</summary>
    public T{#NAMESPACE}Namespace()
    {
    }

    /// NOTE AutoGeneration: This function is all-important!!!
    public override object InitializeLifetimeService()
    {
        return null; // make sure that the T{#NAMESPACE}Namespace object exists until this AppDomain is unloaded!
    }

    {#REMOTEDMETHODS}
    
    {#CLIENTOBJECTFOREACHUICONNECTOR}
}

{##CHECKUSERMODULEPERMISSIONS}
TModuleAccessManager.CheckUserPermissionsForMethod(typeof({#CONNECTORWITHNAMESPACE}), "{#METHODNAME}", "{#PARAMETERTYPES}"{#LEDGERNUMBER});

{##WEBCONNECTORMETHOD}
/// forward the method call
public {#RETURNTYPE} {#METHODNAME}({#PARAMETERDEFINITION})
{
    {#CHECKUSERMODULEPERMISSIONS}
    {#RETURN}{#WEBCONNECTORCLASS}.{#METHODNAME}({#ACTUALPARAMETERS});
}

{##UICONNECTORMETHOD}
/// forward the method call
public {#UICONNECTORINTERFACE} {#METHODNAME}({#PARAMETERDEFINITION})
{
    return ({#UICONNECTORINTERFACE}) TCreateRemotableObject.CreateRemotableObject(
            typeof({#UICONNECTORINTERFACE}),
            typeof({#UICONNECTORCLIENTREMOTINGCLASS}),
            new {#UICONNECTORCLASS}({#ACTUALPARAMETERS}));
}