# see http://www.appveyor.com/docs/appveyor-yml
image: Ubuntu1804
version: 1.0.{build}
platform: x86
stack: mysql, node 10
clone_depth: 1
init: []
environment:
 APPVEYOR_NODE: installed
 APPVEYOR_MONO: installed
 APPVEYOR_MYSQL: installed
 MYSQL_ROOT_PWD: Password12!
install:
#- sudo -E ln -s `which npm` /usr/bin/npm
#- sudo -E chown -R 1001:1001 "/home/appveyor/.npm"
#- sudo sed -i "s/\[mysqld\]/[mysqld]\nskip-name-resolve/g" /etc/mysql/my.cnf && sudo systemctl restart mysql
- curl https://getopenpetra.com > getopenpetra.sh && chmod a+x getopenpetra.sh && sudo -E ./getopenpetra.sh devenv
build_script:
- echo "building was already done in install section"
test_script:
- sudo -E sh -c "curl --silent --location https://github.com/openpetra/demo-databases/raw/UsedForNUnitTests/demoWith1ledger.yml.gz > /home/op_dev/openpetra/demoWith1ledger.yml.gz && chown op_dev:op_dev /home/op_dev/openpetra/demoWith1ledger.yml.gz"
- sudo -E sh -c "cd /home/op_dev/openpetra && nant resetDatabase test-without-display"
before_deploy:
- sudo -E sh -c "cd /home/op_dev/openpetra && nant buildRPM"
