# see http://www.appveyor.com/docs/appveyor-yml
image: Ubuntu1804
version: 1.0.{build}
platform: x86
stack: mysql, node 8
clone_depth: 1
init: []
environment:
 APPVEYOR_NODE: installed
 APPVEYOR_MONO: installed
 APPVEYOR_MARIADB: installed
 MYSQL_ROOT_PWD: Password12!
install:
- curl https://getopenpetra.com > getopenpetra.sh && chmod a+x getopenpetra.sh && sudo -E ./getopenpetra.sh devenv
test_script:
- sudo cd /home/op_dev/openpetra && nant recreateDatabase resetDatabase test-without-display
before_deploy:
- sudo cd /home/op_dev/openpetra && nant buildRPM
