{##DYNAMICTABPAGEUSERCONTROLSETUPMULTIUCPART}
if(Get{#TABCONTROLNAMEWITHOUTPREFIX}VariableUC() == TDynamicLoadableUserControls.dluc{#USERCONTROLNAMEWITHOUTPREFIX})
{    
    {#MULTIUCCODE}    
}
{#ELSESTATEMENT}