//
// DO NOT REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
//
// @Authors:
//       timop
//
// Copyright 2004-2012 by OM International
//
// This file is part of OpenPetra.org.
//
// OpenPetra.org is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// OpenPetra.org is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with OpenPetra.org.  If not, see <http://www.gnu.org/licenses/>.
//
using System;
using System.Xml;
using System.Collections.Specialized;
using System.Collections.Generic;
using Ict.Tools.CodeGeneration;
using Ict.Tools.DBXML;
using Ict.Common.IO;
using Ict.Common;

namespace Ict.Tools.CodeGeneration.ExtJs
{
    /// <summary>
    /// the base for the control generators
    /// </summary>
    public class TControlGenerator : IControlGenerator
    {
        /// <summary>controls with this prefix should be generated by this generator</summary>
        public string FPrefix;
        /// <summary>ext.js type of the control</summary>
        public string FControlType;
        /// <summary>should the control size automatically </summary>
        public bool FAutoSize = false;
        /// <summary>is there a specified location for the control</summary>
        public bool FLocation = true;
        /// <summary>should a label be generated for this control</summary>
        public bool FGenerateLabel = true;

        /// the readonly property eg of Textbox still allows tooltips and copy to clipboard, which enable=false would not allow
        public bool FHasReadOnlyProperty = false;
        /// should the control be added to the parent container
        public bool FAddControlToContainer = true;
        /// <summary>does this control require children</summary>
        public bool FRequiresChildren = false;
        /// <summary>default width for control</summary>
        public Int32 FDefaultWidth = 300;
        /// <summary>default height for control</summary>
        public Int32 FDefaultHeight = 28;
        /// <summary>name of the snippet the defines the code for the control</summary>
        public string FControlDefinitionSnippetName = "ITEMDEFINITION";
        /// <summary>the representation of the code to be generated</summary>
        public static TCodeStorage FCodeStorage;

        /// <summary>
        /// constructor
        /// </summary>
        /// <param name="APrefix"></param>
        /// <param name="AControlType"></param>
        public TControlGenerator(string APrefix, string AControlType)
        {
            FPrefix = APrefix;
            FControlType = AControlType;
        }

        /// <summary>
        /// should this control only be created if there are children controls? eg toolbar
        /// </summary>
        public bool RequiresChildren
        {
            get
            {
                return FRequiresChildren;
            }
        }

        /// <summary>
        /// not implemented for ext.js. labels are done by ext.js
        /// </summary>
        /// <param name="ctrl"></param>
        /// <returns></returns>
        public bool GenerateLabel(TControlDef ctrl)
        {
            // not required for ext.js
            return false;
        }

        /// <summary>
        /// get the type of the control
        /// </summary>
        public String ControlType
        {
            get
            {
                return FControlType;
            }
            set
            {
                FControlType = value;
            }
        }

        /// <summary>
        /// the name of the snippet in the template for Readcontrols and setcontrols, in captial letters
        /// </summary>
        public string TemplateSnippetName
        {
            get
            {
                return "";
            }
            set
            {
            }
        }

        /// <summary>
        /// should the control be added to the parent container
        /// </summary>
        public bool AddControlToContainer
        {
            get
            {
                return FAddControlToContainer;
            }
            set
            {
                FAddControlToContainer = value;
            }
        }

        /// use the prefix to see if the control matches the current class
        public bool SimplePrefixMatch(XmlNode curNode)
        {
            return curNode.Name.StartsWith(FPrefix);
        }

        /// overwrite for more complicated matches,
        /// if the same prefix is used for more than one control type
        /// e.g. txt
        public virtual bool ControlFitsNode(XmlNode curNode)
        {
            return SimplePrefixMatch(curNode);
        }

        /// <summary>
        /// not implemented here
        /// </summary>
        public virtual void ProcessChildren(TFormWriter writer, TControlDef ctrl)
        {
        }

        /// <summary>
        /// not implemented here
        /// </summary>
        public virtual void AddChildren(TFormWriter writer, TControlDef ctrl)
        {
        }

        /// <summary>
        /// not implemented here
        /// </summary>
        public virtual void GenerateControl(TFormWriter writer, TControlDef ctrl)
        {
        }

        /// <summary>
        /// not implemented here
        /// </summary>
        public virtual void GenerateDeclaration(TFormWriter writer, TControlDef ctrl)
        {
        }

        private StringCollection FAlreadyInserted = new StringCollection();

        /// <summary>
        /// fill in the attributes for the control
        /// </summary>
        public virtual ProcessTemplate SetControlProperties(TFormWriter writer, TControlDef ACtrl)
        {
            if (FAlreadyInserted.Contains(ACtrl.controlName))
            {
                throw new Exception("Cannot insert control " + ACtrl.controlName + " several times into a form");
            }

            FAlreadyInserted.Add(ACtrl.controlName);

            ProcessTemplate snippetControl = writer.FTemplate.GetSnippet(FControlDefinitionSnippetName);

            snippetControl.SetCodelet("ITEMNAME", ACtrl.controlName);
            snippetControl.SetCodelet("ITEMID", ACtrl.controlName);
            snippetControl.SetCodelet("XTYPE", FControlType);

            if (ACtrl.HasAttribute("xtype"))
            {
                snippetControl.SetCodelet("XTYPE", ACtrl.GetAttribute("xtype"));
            }

            if (ACtrl.HasAttribute("maxLength"))
            {
                snippetControl.SetCodelet("MAXLENGTH", ACtrl.GetAttribute("maxLength"));
            }

            if (ACtrl.HasAttribute("minLength"))
            {
                snippetControl.SetCodelet("MINLENGTH", ACtrl.GetAttribute("minLength"));
            }

            if (ACtrl.HasAttribute("regex"))
            {
                snippetControl.SetCodelet("REGEX", ACtrl.GetAttribute("regex"));
            }

            ((TExtJsFormsWriter)writer).AddResourceString(snippetControl, "LABEL", ACtrl, ACtrl.Label);
            ((TExtJsFormsWriter)writer).AddResourceString(snippetControl, "HELP", ACtrl, ACtrl.GetAttribute("Help"));

            if (ACtrl.HasAttribute("allowBlank") && (ACtrl.GetAttribute("allowBlank") == "true"))
            {
                snippetControl.SetCodelet("ALLOWBLANK", "true");
            }

            if (ACtrl.HasAttribute("inputType"))
            {
                snippetControl.SetCodelet("INPUTTYPE", ACtrl.GetAttribute("inputType"));
            }

            if (ACtrl.HasAttribute("vtype"))
            {
                snippetControl.SetCodelet("VTYPE", ACtrl.GetAttribute("vtype"));
            }

            if (ACtrl.HasAttribute("DateFormat"))
            {
                snippetControl.SetCodelet("DATEFORMAT", ACtrl.GetAttribute("DateFormat"));
            }

            if (ACtrl.HasAttribute("ShowToday"))
            {
                snippetControl.SetCodelet("SHOWTODAY", ACtrl.GetAttribute("ShowToday"));
            }

            if (ACtrl.HasAttribute("MinDateYear"))
            {
                snippetControl.SetCodelet("MINYEAR", ACtrl.GetAttribute("MinDateYear"));
                snippetControl.SetCodelet("MINMONTH", ACtrl.GetAttribute("MinDateMonth"));
                snippetControl.SetCodelet("MINDAY", ACtrl.GetAttribute("MinDateDay"));
            }

            if (ACtrl.HasAttribute("MaxDateYear"))
            {
                snippetControl.SetCodelet("MAXYEAR", ACtrl.GetAttribute("MaxDateYear"));
                snippetControl.SetCodelet("MAXMONTH", ACtrl.GetAttribute("MaxDateMonth"));
                snippetControl.SetCodelet("MAXDAY", ACtrl.GetAttribute("MaxDateDay"));
            }

            if (ACtrl.HasAttribute("DefaultYear"))
            {
                snippetControl.SetCodelet("DEFAULTYEAR", ACtrl.GetAttribute("DefaultYear"));
                snippetControl.SetCodelet("DEFAULTMONTH", ACtrl.GetAttribute("DefaultMonth"));
                snippetControl.SetCodelet("DEFAULTDAY", ACtrl.GetAttribute("DefaultDay"));
            }

            if (ACtrl.HasAttribute("otherPasswordField"))
            {
                snippetControl.SetCodelet("OTHERPASSWORDFIELD", ACtrl.GetAttribute("otherPasswordField"));
                writer.FTemplate.SetCodelet("PASSWORDTWICE", "yes");
                ((TExtJsFormsWriter)writer).AddResourceString(snippetControl, "strErrorPasswordLength", null,
                    ACtrl.GetAttribute("ValidationErrorLength"));
                ((TExtJsFormsWriter)writer).AddResourceString(snippetControl, "strErrorPasswordNoMatch", null,
                    ACtrl.GetAttribute("ValidationErrorMatching"));
            }

            if (ACtrl.GetAttribute("vtype") == "forcetick")
            {
                writer.FTemplate.SetCodelet("FORCECHECKBOX", "true");
                ((TExtJsFormsWriter)writer).AddResourceString(snippetControl, "strErrorCheckboxRequired", null,
                    ACtrl.GetAttribute("ErrorCheckboxRequired"));
            }

            if (FDefaultWidth != -1)
            {
                snippetControl.SetCodelet("WIDTH", FDefaultWidth.ToString());
            }

            snippetControl.SetCodelet("CUSTOMATTRIBUTES", "");

            return snippetControl;
        }

        /// <summary>
        /// code for the event that the value of the control is changed
        /// </summary>
        public virtual void OnChangeDataType(TFormWriter writer, XmlNode curNode)
        {
            OnChangeDataType(writer, curNode, curNode.Name);
        }

        /// <summary>
        /// code for the event that the value of the control is changed
        /// </summary>
        public virtual void OnChangeDataType(TFormWriter writer, XmlNode curNode, string controlName)
        {
        }

        /// e.g. used for controls on Reports (readparameter, etc)
        public virtual void ApplyDerivedFunctionality(TFormWriter writer, TControlDef control)
        {
        }
    }
}