/*
 * This file is automatically generated, but can also be edited with the Designer
 */

using System;

using Ict.Common.Controls;
using Ict.Petra.Client.CommonControls;

namespace Ict.Petra.Client.MPartner.Gui
{
    partial class TLocationFindDialogWinForm
    {
        /// <summary>
        /// Designer variable used to keep track of non-visual components.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Disposes resources used by the form.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null)
                {
                    components.Dispose();
                }
            }

            base.Dispose(disposing);
        }

        /// <summary>
        /// This method is required for Windows Forms designer support.
        /// Do not change the method contents inside the source code editor. The Forms designer might
        /// not be able to load this method if it was changed manually.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources =
                new System.ComponentModel.ComponentResourceManager(typeof(TLocationFindDialogWinForm));
            this.timerSearchResults = new System.Windows.Forms.Timer(this.components);
            this.grdResult = new Ict.Common.Controls.TSgrdDataGridPaged();
            this.pnlBlankSearchResult = new System.Windows.Forms.Panel();
            this.lblSearchInfo = new System.Windows.Forms.Label();
            this.btnClearCriteria = new System.Windows.Forms.Button();
            this.grpCriteria = new System.Windows.Forms.GroupBox();
            this.pnlLocationKey = new System.Windows.Forms.Panel();
            this.txtLocationKey = new System.Windows.Forms.TextBox();
            this.FFindCriteriaDataTable = new System.Data.DataTable();
            this.DataColumn1 = new System.Data.DataColumn();
            this.DataColumn2 = new System.Data.DataColumn();
            this.DataColumn3 = new System.Data.DataColumn();
            this.DataColumn4 = new System.Data.DataColumn();
            this.DataColumn5 = new System.Data.DataColumn();
            this.DataColumn6 = new System.Data.DataColumn();
            this.DataColumn7 = new System.Data.DataColumn();
            this.DataColumn8 = new System.Data.DataColumn();
            this.DataColumn9 = new System.Data.DataColumn();
            this.DataColumn10 = new System.Data.DataColumn();
            this.DataColumn11 = new System.Data.DataColumn();
            this.DataColumn12 = new System.Data.DataColumn();
            this.DataColumn13 = new System.Data.DataColumn();
            this.DataColumn14 = new System.Data.DataColumn();
            this.lblLocationKey = new System.Windows.Forms.Label();
            this.cmbCountry = new Ict.Petra.Client.CommonControls.TUC_CountryComboBox();
            this.lblCountry = new System.Windows.Forms.Label();
            this.pnlPostCode = new System.Windows.Forms.Panel();
            this.critPostCode = new Ict.Petra.Client.CommonControls.SplitButton();
            this.txtPostCode = new System.Windows.Forms.TextBox();
            this.lblPostCode = new System.Windows.Forms.Label();
            this.pnlCity = new System.Windows.Forms.Panel();
            this.critCity = new Ict.Petra.Client.CommonControls.SplitButton();
            this.txtCity = new System.Windows.Forms.TextBox();
            this.lblCity = new System.Windows.Forms.Label();
            this.pnlAddr2 = new System.Windows.Forms.Panel();
            this.critAddress2 = new Ict.Petra.Client.CommonControls.SplitButton();
            this.txtAddress2 = new System.Windows.Forms.TextBox();
            this.lblStreet2 = new System.Windows.Forms.Label();
            this.pnlAddr3 = new System.Windows.Forms.Panel();
            this.critAddress3 = new Ict.Petra.Client.CommonControls.SplitButton();
            this.txtAddress3 = new System.Windows.Forms.TextBox();
            this.lblAddr3 = new System.Windows.Forms.Label();
            this.lblCounty = new System.Windows.Forms.Label();
            this.pnlAddr1 = new System.Windows.Forms.Panel();
            this.critAddress1 = new Ict.Petra.Client.CommonControls.SplitButton();
            this.txtAddress1 = new System.Windows.Forms.TextBox();
            this.lblAddr1 = new System.Windows.Forms.Label();
            this.dsCriteria = new System.Data.DataSet();
            this.btnSearch = new System.Windows.Forms.Button();
            this.grpResult = new System.Windows.Forms.GroupBox();
            this.tlpAllCriteria = new System.Windows.Forms.TableLayoutPanel();
            this.tlpLeftCritera = new System.Windows.Forms.TableLayoutPanel();
            this.tlpRightCriteria = new System.Windows.Forms.TableLayoutPanel();
            this.critCounty = new Ict.Petra.Client.CommonControls.SplitButton();
            this.lneCriteriaDivider = new DevAge.Windows.Forms.Line();
            this.txtCounty = new System.Windows.Forms.TextBox();
            this.pnlCounty = new System.Windows.Forms.Panel();
            this.stbMain = new Ict.Common.Controls.TExtStatusBarHelp();
            this.btnOK = new System.Windows.Forms.Button();
            this.btnCancel = new System.Windows.Forms.Button();
            this.btnHelp = new System.Windows.Forms.Button();
            this.pnlBtnOKCancelHelpLayout = new System.Windows.Forms.Panel();
            this.pnlBtnOKCancelHelpLayout.SuspendLayout();
//              ((System.ComponentModel.ISupportInitialize)(this.stpInfo)).BeginInit();
            this.grpCriteria.SuspendLayout();
            this.pnlBlankSearchResult.SuspendLayout();
            this.pnlLocationKey.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.FFindCriteriaDataTable)).BeginInit();
            this.pnlPostCode.SuspendLayout();
            this.pnlCity.SuspendLayout();
            this.pnlAddr2.SuspendLayout();
            this.pnlAddr3.SuspendLayout();
            this.pnlAddr1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dsCriteria)).BeginInit();
            this.grpResult.SuspendLayout();
            this.tlpAllCriteria.SuspendLayout();
            this.tlpLeftCritera.SuspendLayout();
            this.tlpRightCriteria.SuspendLayout();
            this.pnlCounty.SuspendLayout();
            this.stbMain.SuspendLayout();
            this.SuspendLayout();
            //
            // btnOK
            //
            this.btnOK.Anchor =
                ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnOK.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btnOK.Enabled = false;
            this.btnOK.Location = new System.Drawing.Point(434, 6);
            this.btnOK.Size = new System.Drawing.Size(83, 23);
            this.btnOK.Text = "&Accept";
            //
            // pnlBtnOKCancelHelpLayout
            //
            this.pnlBtnOKCancelHelpLayout.Location = new System.Drawing.Point(0, 389);
            this.pnlBtnOKCancelHelpLayout.Size = new System.Drawing.Size(616, 32);
            //
            // btnCancel
            //
            this.btnCancel.Anchor =
                ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnCancel.Location = new System.Drawing.Point(521, 6);
            this.btnCancel.Size = new System.Drawing.Size(83, 23);
            //
            // btnHelp
            //
            this.btnHelp.Anchor =
                ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.btnHelp.Location = new System.Drawing.Point(12, 6);
            this.btnHelp.Size = new System.Drawing.Size(83, 23);
//              this.sbtForm.SetStatusBarText(this.btnHelp, "Help");
            //
            // stbMain
            //
            this.stbMain.Location = new System.Drawing.Point(0, 421);
            this.stbMain.Size = new System.Drawing.Size(616, 24);
            //
            // stpInfo
            //
//              this.stpInfo.Width = 616;
            //
            // timerSearchResults
            //
            this.timerSearchResults.Interval = 500;
            this.timerSearchResults.Tick += new System.EventHandler(this.TimerSearchResults_Tick);
            //
            // pnlBlankSearchResult
            //
            this.pnlBlankSearchResult.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this.pnlBlankSearchResult.Controls.Add(this.lblSearchInfo);
            this.pnlBlankSearchResult.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlBlankSearchResult.Location = new System.Drawing.Point(6, 17);
            this.pnlBlankSearchResult.Name = "pnlBlankSearchResult";
            this.pnlBlankSearchResult.Size = new System.Drawing.Size(580, 205);
            this.pnlBlankSearchResult.TabIndex = 5;
            //
            // lblGridMessage
            //
            this.lblSearchInfo.Anchor =
                ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) |
                                                       System.Windows.Forms.AnchorStyles.Left) |
                                                      System.Windows.Forms.AnchorStyles.Right)));
            this.lblSearchInfo.Font =
                new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblSearchInfo.ForeColor = System.Drawing.SystemColors.ControlDarkDark;
            this.lblSearchInfo.Location = new System.Drawing.Point(0, -4);
            this.lblSearchInfo.Name = "lblSearchInfo";
            this.lblSearchInfo.Size = new System.Drawing.Size(584, 208);
            this.lblSearchInfo.TabIndex = 0;
            this.lblSearchInfo.Text = "Searching...";
            this.lblSearchInfo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            //
            // btnClearCriteria
            //
            this.btnClearCriteria.Anchor =
                ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnClearCriteria.Image = ((System.Drawing.Image)(resources.GetObject("btnClearCriteria.Image")));
            this.btnClearCriteria.Location = new System.Drawing.Point(622, 118);
            this.btnClearCriteria.Name = "btnClearCriteria";
            this.btnClearCriteria.Size = new System.Drawing.Size(83, 23);
            this.btnClearCriteria.TabIndex = 2;
            this.btnClearCriteria.Text = "Clea&r";
            this.btnClearCriteria.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnClearCriteria.Click += new System.EventHandler(this.BtnClearCriteria_Click);
            //
            // grpCriteria
            //
            this.grpCriteria.Anchor =
                ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) |
                                                      System.Windows.Forms.AnchorStyles.Right)));
            this.grpCriteria.Controls.Add(this.lneCriteriaDivider);
            this.grpCriteria.Controls.Add(this.tlpAllCriteria);
            this.grpCriteria.Controls.Add(this.btnSearch);
            this.grpCriteria.Controls.Add(this.btnClearCriteria);
//              this.grpCriteria.Dock = System.Windows.Forms.DockStyle.Top;
            this.grpCriteria.Location = new System.Drawing.Point(12, 12);
            this.grpCriteria.Name = "grpCriteria";
            this.grpCriteria.Padding = new System.Windows.Forms.Padding(8, 4, 8, 3);
            this.grpCriteria.Size = new System.Drawing.Size(714, 146);
            this.grpCriteria.TabIndex = 0;
            this.grpCriteria.TabStop = false;
            this.grpCriteria.Text = "&Find Criteria";
            //
            // dtCriteria
            //
            this.FFindCriteriaDataTable.Columns.AddRange(new System.Data.DataColumn[] {
                    this.DataColumn1,
                    this.DataColumn2,
                    this.DataColumn3,
                    this.DataColumn4,
                    this.DataColumn5,
                    this.DataColumn6,
                    this.DataColumn7,
                    this.DataColumn8,
                    this.DataColumn9,
                    this.DataColumn10,
                    this.DataColumn11,
                    this.DataColumn12,
                    this.DataColumn13,
                    this.DataColumn14
                });
            this.FFindCriteriaDataTable.TableName = "Criteria";
            //
            // DataColumn1
            //
            this.DataColumn1.ColumnName = "Addr1";
            this.DataColumn1.DefaultValue = "";
            //
            // DataColumn2
            //
            this.DataColumn2.ColumnName = "Addr1Match";
            this.DataColumn2.DefaultValue = "BEGINS";
            //
            // DataColumn3
            //
            this.DataColumn3.ColumnName = "Street2";
            this.DataColumn3.DefaultValue = "";
            //
            // DataColumn4
            //
            this.DataColumn4.ColumnName = "Street2Match";
            this.DataColumn4.DefaultValue = "BEGINS";
            //
            // DataColumn5
            //
            this.DataColumn5.ColumnName = "Addr3";
            this.DataColumn5.DefaultValue = "";
            //
            // DataColumn6
            //
            this.DataColumn6.ColumnName = "Addr3Match";
            this.DataColumn6.DefaultValue = "BEGINS";
            //
            // DataColumn7
            //
            this.DataColumn7.ColumnName = "City";
            this.DataColumn7.DefaultValue = "";
            //
            // DataColumn8
            //
            this.DataColumn8.ColumnName = "CityMatch";
            this.DataColumn8.DefaultValue = "BEGINS";
            //
            // DataColumn9
            //
            this.DataColumn9.ColumnName = "PostCode";
            this.DataColumn9.DefaultValue = "";
            //
            // DataColumn10
            //
            this.DataColumn10.ColumnName = "PostCodeMatch";
            this.DataColumn10.DefaultValue = "BEGINS";
            //
            // DataColumn11
            //
            this.DataColumn11.ColumnName = "Country";
            this.DataColumn11.DefaultValue = "";
            //
            // DataColumn12
            //
            this.DataColumn12.ColumnName = "LocationKey";
            this.DataColumn12.DefaultValue = "";
            //
            // DataColumn13
            //
            this.DataColumn13.ColumnName = "County";
            this.DataColumn13.DefaultValue = "";
            //
            // DataColumn14
            //
            this.DataColumn14.ColumnName = "CountyMatch";
            this.DataColumn14.DefaultValue = "BEGINS";
            //
            // lblPostCode
            //
            this.lblPostCode.AutoSize = true;
            this.lblPostCode.Location = new System.Drawing.Point(3, 3);
            this.lblPostCode.Margin = new System.Windows.Forms.Padding(3, 3, 3, 0);
            this.lblPostCode.Name = "lblPostCode";
            this.lblPostCode.Size = new System.Drawing.Size(70, 13);
            this.lblPostCode.TabIndex = 0;
            this.lblPostCode.Text = "P&ost Code:";
            this.lblPostCode.TextAlign = System.Drawing.ContentAlignment.TopRight;
            //
            // pnlPostCode
            //
            this.pnlPostCode.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
//              this.pnlPostCode.Controls.Add(this.critPostCode);
            this.pnlPostCode.Controls.Add(this.txtPostCode);
            this.pnlPostCode.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlPostCode.Location = new System.Drawing.Point(91, 0);
            this.pnlPostCode.Margin = new System.Windows.Forms.Padding(0);
            this.pnlPostCode.Name = "pnlPostCode";
            this.pnlPostCode.Size = new System.Drawing.Size(209, 22);
            this.pnlPostCode.TabIndex = 1;
            //
            // critPostCode
            //
            this.critPostCode.ControlMode = Ict.Petra.Client.CommonControls.TControlMode.Matches;
            this.critPostCode.DataBindings.Add(new System.Windows.Forms.Binding("SelectedValue", this.FFindCriteriaDataTable, "PostCodeMatch", true));
            this.critPostCode.Dock = System.Windows.Forms.DockStyle.Fill;
            this.critPostCode.Location = new System.Drawing.Point(150, 0);
            this.critPostCode.Margin = new System.Windows.Forms.Padding(0);
            this.critPostCode.MaximumSize = new System.Drawing.Size(42, 22);
            this.critPostCode.Name = "critPostCode";
            this.critPostCode.Padding = new System.Windows.Forms.Padding(3, 2, 0, 2);
            this.critPostCode.SelectedValue = "BEGINS";
            this.critPostCode.Size = new System.Drawing.Size(42, 22);
            this.critPostCode.TabIndex = 2;
            this.critPostCode.TabStop = false;
            //
            // txtPostCode
            //
            this.txtPostCode.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.FFindCriteriaDataTable, "PostCode", true));
            this.txtPostCode.Dock = System.Windows.Forms.DockStyle.Left;
            this.txtPostCode.Font =
                new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPostCode.Location = new System.Drawing.Point(0, 0);
            this.txtPostCode.Margin = new System.Windows.Forms.Padding(0);
            this.txtPostCode.Name = "txtPostCode";
            this.txtPostCode.Size = new System.Drawing.Size(250, 21);
            this.txtPostCode.TabIndex = 1;
            this.txtPostCode.KeyUp += new System.Windows.Forms.KeyEventHandler(this.TxtPostCode_KeyUp);
            this.txtPostCode.Leave += new EventHandler(this.TxtPostCode_Leave);
            //
            // pnlCounty
            //
//              this.pnlCounty.Controls.Add(this.critCounty);
            this.pnlCounty.Controls.Add(this.txtCounty);
            this.pnlCounty.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlCounty.Location = new System.Drawing.Point(91, 22);
            this.pnlCounty.Margin = new System.Windows.Forms.Padding(0);
            this.pnlCounty.Name = "pnlCounty";
            this.pnlCounty.Size = new System.Drawing.Size(209, 22);
            this.pnlCounty.TabIndex = 3;
            //
            // critCounty
            //
            this.critCounty.ControlMode = Ict.Petra.Client.CommonControls.TControlMode.Matches;
            this.critCounty.DataBindings.Add(new System.Windows.Forms.Binding("SelectedValue", this.FFindCriteriaDataTable, "CountyMatch", true));
            this.critCounty.Dock = System.Windows.Forms.DockStyle.Fill;
            this.critCounty.Location = new System.Drawing.Point(150, 0);
            this.critCounty.Margin = new System.Windows.Forms.Padding(0);
            this.critCounty.MaximumSize = new System.Drawing.Size(42, 0);
            this.critCounty.MinimumSize = new System.Drawing.Size(42, 22);
            this.critCounty.Name = "critCounty";
            this.critCounty.Padding = new System.Windows.Forms.Padding(3, 2, 0, 2);
            this.critCounty.SelectedValue = "BEGINS";
            this.critCounty.Size = new System.Drawing.Size(42, 22);
            this.critCounty.TabIndex = 3;
            this.critCounty.TabStop = false;
            //
            // lblCounty
            //
            this.lblCounty.AutoSize = true;
            this.lblCounty.Location = new System.Drawing.Point(3, 25);
            this.lblCounty.Margin = new System.Windows.Forms.Padding(3, 3, 3, 0);
            this.lblCounty.Name = "lblCounty";
            this.lblCounty.Size = new System.Drawing.Size(53, 13);
            this.lblCounty.TabIndex = 2;
            this.lblCounty.Text = "Co&unty:";
            this.lblCounty.TextAlign = System.Drawing.ContentAlignment.TopRight;
            //
            // txtCounty
            //
            this.txtCounty.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.FFindCriteriaDataTable, "County", true));
            this.txtCounty.Dock = System.Windows.Forms.DockStyle.Left;
            this.txtCounty.Font =
                new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCounty.Location = new System.Drawing.Point(0, 0);
            this.txtCounty.Margin = new System.Windows.Forms.Padding(0);
            this.txtCounty.Name = "txtCounty";
            this.txtCounty.Size = new System.Drawing.Size(250, 21);
            this.txtCounty.TabIndex = 0;
            this.txtCounty.KeyUp += new System.Windows.Forms.KeyEventHandler(this.TxtCounty_KeyUp);
            this.txtCounty.Leave += new EventHandler(this.TxtCounty_Leave);
            //
            // lblCountry
            //
            this.lblCountry.AutoSize = true;
            this.lblCountry.Location = new System.Drawing.Point(3, 47);
            this.lblCountry.Margin = new System.Windows.Forms.Padding(3, 3, 3, 0);
            this.lblCountry.Name = "lblCountry";
            this.lblCountry.Size = new System.Drawing.Size(58, 13);
            this.lblCountry.TabIndex = 4;
            this.lblCountry.Text = "Co&untry:";
            this.lblCountry.TextAlign = System.Drawing.ContentAlignment.TopRight;
            //
            // cmbCountry
            //
            this.cmbCountry.Location = new System.Drawing.Point(91, 44);
            this.cmbCountry.Margin = new System.Windows.Forms.Padding(0);
            this.cmbCountry.Name = "cmbCountry";
            this.cmbCountry.SelectedValue = null;
            this.cmbCountry.Size = new System.Drawing.Size(196, 22);
            this.cmbCountry.TabIndex = 5;
            this.cmbCountry.SelectedValueChanged += new EventHandler(this.UcoCountryComboBox_SelectedValueChanged);
            //
            // lblLocationKey
            //
            this.lblLocationKey.AutoSize = true;
            this.lblLocationKey.Location = new System.Drawing.Point(3, 69);
            this.lblLocationKey.Margin = new System.Windows.Forms.Padding(3, 3, 3, 0);
            this.lblLocationKey.Name = "lblLocationKey";
            this.lblLocationKey.Size = new System.Drawing.Size(85, 13);
            this.lblLocationKey.TabIndex = 6;
            this.lblLocationKey.Text = "Location &Key:";
            this.lblLocationKey.TextAlign = System.Drawing.ContentAlignment.TopRight;
            //
            // pnlLocationKey
            //
            this.pnlLocationKey.Controls.Add(this.txtLocationKey);
            this.pnlLocationKey.Location = new System.Drawing.Point(91, 66);
            this.pnlLocationKey.Margin = new System.Windows.Forms.Padding(0);
            this.pnlLocationKey.Name = "pnlLocationKey";
            this.pnlLocationKey.Size = new System.Drawing.Size(192, 22);
            this.pnlLocationKey.TabIndex = 7;
            //
            // txtLocationKey
            //
            this.txtLocationKey.Anchor =
                ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) |
                                                      System.Windows.Forms.AnchorStyles.Right)));
            this.txtLocationKey.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.FFindCriteriaDataTable, "LocationKey", true));
            this.txtLocationKey.Font =
                new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtLocationKey.Location = new System.Drawing.Point(0, 0);
            this.txtLocationKey.Name = "txtLocationKey";
            this.txtLocationKey.Size = new System.Drawing.Size(70, 21);
            this.txtLocationKey.TabIndex = 0;
            this.txtLocationKey.KeyUp += new System.Windows.Forms.KeyEventHandler(this.TxtLocationKey_KeyUp);
            this.txtLocationKey.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.TxtLocationKey_KeyPress);
            //
            // pnlCity
            //
            this.pnlCity.AutoSize = true;
            this.pnlCity.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
//              this.pnlCity.Controls.Add(this.critCity);
            this.pnlCity.Controls.Add(this.txtCity);
            this.pnlCity.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlCity.Location = new System.Drawing.Point(75, 66);
            this.pnlCity.Margin = new System.Windows.Forms.Padding(0);
            this.pnlCity.Name = "pnlCity";
            this.pnlCity.Size = new System.Drawing.Size(225, 22);
            this.pnlCity.TabIndex = 3;
            //
            // lblCity
            //
            this.lblCity.AutoSize = true;
            this.lblCity.Location = new System.Drawing.Point(3, 69);
            this.lblCity.Margin = new System.Windows.Forms.Padding(3, 3, 3, 0);
            this.lblCity.Name = "lblCity";
            this.lblCity.Padding = new System.Windows.Forms.Padding(0, 3, 0, 0);
            this.lblCity.Size = new System.Drawing.Size(35, 16);
            this.lblCity.TabIndex = 3;
            this.lblCity.Text = "Cit&y/Town:";
            this.lblCity.TextAlign = System.Drawing.ContentAlignment.TopRight;
            //
            // txtCity
            //
            this.txtCity.Anchor =
                ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) |
                                                      System.Windows.Forms.AnchorStyles.Right)));
            this.txtCity.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.FFindCriteriaDataTable, "City", true));
            this.txtCity.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCity.Location = new System.Drawing.Point(0, 0);
            this.txtCity.Name = "txtCity";
            this.txtCity.Size = new System.Drawing.Size(210, 21);
            this.txtCity.TabIndex = 0;
            this.txtCity.KeyUp += new System.Windows.Forms.KeyEventHandler(this.TxtCity_KeyUp);
            this.txtCity.Leave += new EventHandler(this.TxtCity_Leave);
            //
            // critCity
            //
            this.critCity.Anchor =
                ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.critCity.ControlMode = Ict.Petra.Client.CommonControls.TControlMode.Matches;
            this.critCity.DataBindings.Add(new System.Windows.Forms.Binding("SelectedValue", this.FFindCriteriaDataTable, "CityMatch", true));
            this.critCity.Location = new System.Drawing.Point(153, 2);
            this.critCity.Name = "critCity";
            this.critCity.SelectedValue = "BEGINS";
            this.critCity.Size = new System.Drawing.Size(42, 18);
            this.critCity.TabIndex = 2;
            this.critCity.TabStop = false;
            //
            // pnlStreet2
            //
            this.pnlAddr2.AutoSize = true;
            this.pnlAddr2.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
//              this.pnlAddr2.Controls.Add(this.critAddress2);
            this.pnlAddr2.Controls.Add(this.txtAddress2);
            this.pnlAddr2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlAddr2.Location = new System.Drawing.Point(75, 22);
            this.pnlAddr2.Margin = new System.Windows.Forms.Padding(0);
            this.pnlAddr2.Name = "pnlStreet2";
            this.pnlAddr2.Size = new System.Drawing.Size(225, 22);
            this.pnlAddr2.TabIndex = 1;
            //
            // critStreet2
            //
            this.critAddress2.Anchor =
                ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.critAddress2.ControlMode = Ict.Petra.Client.CommonControls.TControlMode.Matches;
            this.critAddress2.DataBindings.Add(new System.Windows.Forms.Binding("SelectedValue", this.FFindCriteriaDataTable, "Street2Match", true));
            this.critAddress2.Location = new System.Drawing.Point(153, 2);
            this.critAddress2.Name = "critStreet2";
            this.critAddress2.SelectedValue = "BEGINS";
            this.critAddress2.Size = new System.Drawing.Size(42, 18);
            this.critAddress2.TabIndex = 2;
            this.critAddress2.TabStop = false;
            //
            // txtStreet2
            //
            this.txtAddress2.Anchor =
                ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) |
                                                      System.Windows.Forms.AnchorStyles.Right)));
            this.txtAddress2.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.FFindCriteriaDataTable, "Street2", true));
            this.txtAddress2.Font =
                new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtAddress2.Location = new System.Drawing.Point(0, 0);
            this.txtAddress2.Name = "txtStreet2";
            this.txtAddress2.Size = new System.Drawing.Size(210, 21);
            this.txtAddress2.TabIndex = 0;
            this.txtAddress2.KeyUp += new System.Windows.Forms.KeyEventHandler(this.TxtAddress2_KeyUp);
            this.txtAddress2.Leave += new EventHandler(this.TxtAddress2_Leave);
            //
            // lblStreet2
            //
            this.lblStreet2.AutoSize = true;
            this.lblStreet2.Location = new System.Drawing.Point(3, 25);
            this.lblStreet2.Margin = new System.Windows.Forms.Padding(3, 3, 3, 0);
            this.lblStreet2.Name = "lblStreet2";
            this.lblStreet2.Padding = new System.Windows.Forms.Padding(0, 3, 0, 0);
            this.lblStreet2.Size = new System.Drawing.Size(69, 15);
            this.lblStreet2.TabIndex = 1;
            this.lblStreet2.Text = "Address &2:";
            this.lblStreet2.TextAlign = System.Drawing.ContentAlignment.TopRight;
            //
            // pnlAddr3
            //
            this.pnlAddr3.AutoSize = true;
            this.pnlAddr3.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
//              this.pnlAddr3.Controls.Add(this.critAddress3);
            this.pnlAddr3.Controls.Add(this.txtAddress3);
            this.pnlAddr3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlAddr3.Location = new System.Drawing.Point(75, 44);
            this.pnlAddr3.Margin = new System.Windows.Forms.Padding(0);
            this.pnlAddr3.Name = "pnlAddr3";
            this.pnlAddr3.Size = new System.Drawing.Size(225, 22);
            this.pnlAddr3.TabIndex = 2;
            //
            // critAddr3
            //
            this.critAddress3.Anchor =
                ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.critAddress3.ControlMode = Ict.Petra.Client.CommonControls.TControlMode.Matches;
            this.critAddress3.DataBindings.Add(new System.Windows.Forms.Binding("SelectedValue", this.FFindCriteriaDataTable, "Addr3Match", true));
            this.critAddress3.Location = new System.Drawing.Point(153, 2);
            this.critAddress3.Name = "critAddr3";
            this.critAddress3.SelectedValue = "BEGINS";
            this.critAddress3.Size = new System.Drawing.Size(42, 18);
            this.critAddress3.TabIndex = 2;
            this.critAddress3.TabStop = false;
            //
            // txtAddr3
            //
            this.txtAddress3.Anchor =
                ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) |
                                                      System.Windows.Forms.AnchorStyles.Right)));
            this.txtAddress3.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.FFindCriteriaDataTable, "Addr3", true));
            this.txtAddress3.Font =
                new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtAddress3.Location = new System.Drawing.Point(0, 0);
            this.txtAddress3.Name = "txtAddr3";
            this.txtAddress3.Size = new System.Drawing.Size(210, 21);
            this.txtAddress3.TabIndex = 0;
            this.txtAddress3.KeyUp += new System.Windows.Forms.KeyEventHandler(this.TxtAddress3_KeyUp);
            this.txtAddress3.Leave += new EventHandler(this.TxtAddress3_Leave);
            //
            // lblAddr3
            //
            this.lblAddr3.AutoSize = true;
            this.lblAddr3.Location = new System.Drawing.Point(3, 47);
            this.lblAddr3.Margin = new System.Windows.Forms.Padding(3, 3, 3, 0);
            this.lblAddr3.Name = "lblAddr3";
            this.lblAddr3.Padding = new System.Windows.Forms.Padding(0, 3, 0, 0);
            this.lblAddr3.Size = new System.Drawing.Size(69, 16);
            this.lblAddr3.TabIndex = 2;
            this.lblAddr3.Text = "Address &3:";
            this.lblAddr3.TextAlign = System.Drawing.ContentAlignment.TopRight;
            //
            // pnlAddr1
            //
            this.pnlAddr1.AutoSize = true;
            this.pnlAddr1.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
//              this.pnlAddr1.Controls.Add(this.critAddress1);
            this.pnlAddr1.Controls.Add(this.txtAddress1);
            this.pnlAddr1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlAddr1.Location = new System.Drawing.Point(75, 0);
            this.pnlAddr1.Margin = new System.Windows.Forms.Padding(0);
            this.pnlAddr1.Name = "Panel1";
            this.pnlAddr1.Size = new System.Drawing.Size(225, 22);
            this.pnlAddr1.TabIndex = 0;
            //
            // critAddr1
            //
            this.critAddress1.Anchor =
                ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.critAddress1.ControlMode = Ict.Petra.Client.CommonControls.TControlMode.Matches;
            this.critAddress1.DataBindings.Add(new System.Windows.Forms.Binding("SelectedValue", this.FFindCriteriaDataTable, "Addr1Match", true));
            this.critAddress1.Location = new System.Drawing.Point(153, 2);
            this.critAddress1.Name = "critAddr1";
            this.critAddress1.SelectedValue = "BEGINS";
            this.critAddress1.Size = new System.Drawing.Size(42, 18);
            this.critAddress1.TabIndex = 2;
            this.critAddress1.TabStop = false;
            //
            // txtAddr1
            //
            this.txtAddress1.Anchor =
                ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) |
                                                      System.Windows.Forms.AnchorStyles.Right)));
            this.txtAddress1.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.FFindCriteriaDataTable, "Addr1", true));
            this.txtAddress1.Font =
                new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtAddress1.Location = new System.Drawing.Point(0, 0);
            this.txtAddress1.Name = "txtAddr1";
            this.txtAddress1.Size = new System.Drawing.Size(210, 21);
            this.txtAddress1.TabIndex = 0;
            this.txtAddress1.KeyUp += new System.Windows.Forms.KeyEventHandler(this.TxtAddress1_KeyUp);
            this.txtAddress1.Leave += new EventHandler(this.TxtAddress1_Leave);
            //
            // lblAddr1
            //
            this.lblAddr1.AutoSize = true;
            this.lblAddr1.Location = new System.Drawing.Point(3, 3);
            this.lblAddr1.Margin = new System.Windows.Forms.Padding(3, 3, 3, 0);
            this.lblAddr1.Name = "lblAddr1";
            this.lblAddr1.Size = new System.Drawing.Size(69, 13);
            this.lblAddr1.TabIndex = 0;
            this.lblAddr1.Text = "Address &1:";
            this.lblAddr1.TextAlign = System.Drawing.ContentAlignment.TopRight;
            //
            // dsCriteria
            //
            this.dsCriteria.DataSetName = "CriteriaDataSet";
            this.dsCriteria.Locale = new System.Globalization.CultureInfo("en-GB");
            this.dsCriteria.Tables.AddRange(new System.Data.DataTable[] {
                    this.FFindCriteriaDataTable
                });
            //
            // btnSearch
            //
            this.btnSearch.Image = ((System.Drawing.Image)(resources.GetObject("btnSearch.Image")));
            this.btnSearch.Location = new System.Drawing.Point(8, 118);
            this.btnSearch.Name = "btnSearch";
            this.btnSearch.Size = new System.Drawing.Size(83, 23);
            this.btnSearch.TabIndex = 1;
            this.btnSearch.Text = " &Search";
            this.btnSearch.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.btnSearch.Click += new System.EventHandler(this.BtnSearch_Click);
            //
            // grpResult
            //
            this.grpResult.Anchor =
                ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) |
                                                       System.Windows.Forms.AnchorStyles.Left) |
                                                      System.Windows.Forms.AnchorStyles.Right)));
            this.grpResult.Controls.Add(this.pnlBlankSearchResult);
            this.grpResult.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.grpResult.Location = new System.Drawing.Point(12, 162);
            this.grpResult.Name = "grpResult";
            this.grpResult.Padding = new System.Windows.Forms.Padding(6, 3, 6, 4);
            this.grpResult.Size = new System.Drawing.Size(714, 225);
            this.grpResult.TabIndex = 1;
            this.grpResult.TabStop = false;
            this.grpResult.Text = "Find R&esult";
            //
            // tlpAllCriteria
            //
            this.tlpAllCriteria.AutoSize = true;
            this.tlpAllCriteria.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.tlpAllCriteria.ColumnCount = 2;
            this.tlpAllCriteria.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tlpAllCriteria.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tlpAllCriteria.Controls.Add(this.tlpRightCriteria, 1, 0);
            this.tlpAllCriteria.Controls.Add(this.tlpLeftCritera, 0, 0);
            this.tlpAllCriteria.Dock = System.Windows.Forms.DockStyle.Top;
            this.tlpAllCriteria.Location = new System.Drawing.Point(8, 18);
            this.tlpAllCriteria.Name = "tlpAllCriteria";
            this.tlpAllCriteria.RowCount = 1;
            this.tlpAllCriteria.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpAllCriteria.Size = new System.Drawing.Size(576, 94);
            this.tlpAllCriteria.TabIndex = 0;
            //
            // tlpLeftCritera
            //
            this.tlpLeftCritera.AutoSize = true;
            this.tlpLeftCritera.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.tlpLeftCritera.ColumnCount = 2;
            this.tlpLeftCritera.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tlpLeftCritera.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpLeftCritera.Controls.Add(this.lblStreet2, 0, 1);
            this.tlpLeftCritera.Controls.Add(this.lblAddr1, 0, 0);
            this.tlpLeftCritera.Controls.Add(this.pnlAddr1, 1, 0);
            this.tlpLeftCritera.Controls.Add(this.lblAddr3, 0, 2);
            this.tlpLeftCritera.Controls.Add(this.pnlAddr3, 1, 2);
            this.tlpLeftCritera.Controls.Add(this.pnlAddr2, 1, 1);
            this.tlpLeftCritera.Controls.Add(this.lblCity, 0, 3);
            this.tlpLeftCritera.Controls.Add(this.pnlCity, 1, 3);
            this.tlpLeftCritera.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpLeftCritera.Location = new System.Drawing.Point(3, 3);
            this.tlpLeftCritera.MinimumSize = new System.Drawing.Size(300, 0);
            this.tlpLeftCritera.Name = "tlpLeftCritera";
            this.tlpLeftCritera.RowCount = 4;
            this.tlpLeftCritera.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 22F));
            this.tlpLeftCritera.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 22F));
            this.tlpLeftCritera.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 22F));
            this.tlpLeftCritera.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 22F));
            this.tlpLeftCritera.Size = new System.Drawing.Size(300, 88);
            this.tlpLeftCritera.TabIndex = 0;
            //
            // tlpRightCriteria
            //
            this.tlpRightCriteria.AutoSize = true;
            this.tlpRightCriteria.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.tlpRightCriteria.ColumnCount = 2;
            this.tlpRightCriteria.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            this.tlpRightCriteria.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tlpRightCriteria.Controls.Add(this.pnlCounty, 1, 1);
            this.tlpRightCriteria.Controls.Add(this.pnlLocationKey, 1, 3);
            this.tlpRightCriteria.Controls.Add(this.pnlPostCode, 1, 0);
            this.tlpRightCriteria.Controls.Add(this.cmbCountry, 1, 2);
            this.tlpRightCriteria.Controls.Add(this.lblLocationKey, 0, 3);
            this.tlpRightCriteria.Controls.Add(this.lblCounty, 0, 1);
            this.tlpRightCriteria.Controls.Add(this.lblCountry, 0, 2);
            this.tlpRightCriteria.Controls.Add(this.lblPostCode, 0, 0);
            this.tlpRightCriteria.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpRightCriteria.Location = new System.Drawing.Point(291, 3);
            this.tlpRightCriteria.MinimumSize = new System.Drawing.Size(300, 0);
            this.tlpRightCriteria.Name = "tlpRightCriteria";
            this.tlpRightCriteria.RowCount = 4;
            this.tlpRightCriteria.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 22F));
            this.tlpRightCriteria.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 22F));
            this.tlpRightCriteria.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 22F));
            this.tlpRightCriteria.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 22F));
            this.tlpRightCriteria.Size = new System.Drawing.Size(300, 88);
            this.tlpRightCriteria.TabIndex = 1;
            //
            // lneCriteriaDivider
            //
            this.lneCriteriaDivider.Anchor =
                ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) |
                                                      System.Windows.Forms.AnchorStyles.Right)));
            this.lneCriteriaDivider.DashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            this.lneCriteriaDivider.FirstColor = System.Drawing.SystemColors.ControlDark;
            this.lneCriteriaDivider.LineStyle = DevAge.Windows.Forms.LineStyle.Horizontal;
            this.lneCriteriaDivider.Location = new System.Drawing.Point(6, 114);
            this.lneCriteriaDivider.Margin = new System.Windows.Forms.Padding(3, 0, 3, 3);
            this.lneCriteriaDivider.Name = "lneCriteriaDivider";
            this.lneCriteriaDivider.SecondColor = System.Drawing.SystemColors.ControlLightLight;
            this.lneCriteriaDivider.Size = new System.Drawing.Size(642, 2);
            this.lneCriteriaDivider.TabIndex = 10;
            this.lneCriteriaDivider.TabStop = false;
            //
            // stbMain
            //
            this.stbMain.Name = "stbMain";
            this.stbMain.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.stbMain.Size = new System.Drawing.Size(10, 24);
            //
            // btnOK
            //
            this.btnOK.Anchor =
                ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnOK.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.btnOK.Location = new System.Drawing.Point(233, 4);
            this.btnOK.Name = "btnOK";
            this.btnOK.Size = new System.Drawing.Size(76, 24);
//              this.sbtForm.SetStatusBarText(this.btnOK, "Accept data and continue");
            this.btnOK.TabIndex = 997;
            this.btnOK.Text = "&Accept";
            this.btnOK.Click += new System.EventHandler(this.BtnOK_Click);
            //
            // btnCancel
            //
            this.btnCancel.Anchor =
                ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnCancel.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.btnCancel.Location = new System.Drawing.Point(315, 4);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(76, 24);
//              this.sbtForm.SetStatusBarText(this.btnCancel, "Cancel data entry and close");
            this.btnCancel.TabIndex = 998;
            this.btnCancel.Text = "&Cancel";
            //
            // btnHelp
            //
            this.btnHelp.Anchor =
                ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
//              this.btnHelp.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.btnHelp.Location = new System.Drawing.Point(11, 4);
            this.btnHelp.Name = "btnHelp";
            this.btnHelp.Size = new System.Drawing.Size(27, 24);
//              this.sbtForm.SetStatusBarText(this.btnHelp, "Help");
            this.btnHelp.Image = ((System.Drawing.Bitmap)resources.GetObject("btnHelp.Image"));
            this.btnHelp.TabIndex = 999;
            this.btnHelp.Text = "";
            this.btnHelp.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnHelp.Click += new System.EventHandler(this.BtnHelp_Click);
            //
            // pnlBtnOKCancelHelpLayout
            //
            this.pnlBtnOKCancelHelpLayout.Controls.Add(this.btnHelp);
            this.pnlBtnOKCancelHelpLayout.Controls.Add(this.btnOK);
            this.pnlBtnOKCancelHelpLayout.Controls.Add(this.btnCancel);
            this.pnlBtnOKCancelHelpLayout.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.pnlBtnOKCancelHelpLayout.Location = new System.Drawing.Point(0, 190);
            this.pnlBtnOKCancelHelpLayout.Name = "pnlBtnOKCancelHelpLayout";
            this.pnlBtnOKCancelHelpLayout.Size = new System.Drawing.Size(402, 32);
            this.pnlBtnOKCancelHelpLayout.TabIndex = 996;
            //
            // TLocationFindDialogWinForm
            //
//              this.AcceptButton = this.btnSearch;
            this.AutoScaleBaseSize = new System.Drawing.Size(6, 14);
            this.CancelButton = this.btnCancel;
            this.ClientSize = new System.Drawing.Size(738, 445);
            this.Controls.Add(this.pnlBtnOKCancelHelpLayout);
            this.Controls.Add(this.grpResult);
            this.Controls.Add(this.grpCriteria);
            this.Controls.Add(this.stbMain);
//              this.Padding = new System.Windows.Forms.Padding(10, 10, 10, 10);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.Sizable;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "TLocationFindDialogWinForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Location Find";
            this.KeyPreview = true;
            this.Activated += new System.EventHandler(this.TLocationFindDialogWinForm_Activated);
            this.Load += new System.EventHandler(this.TLocationFindDialogWinForm_Load);
            this.Controls.SetChildIndex(this.grpCriteria, 0);
            this.Controls.SetChildIndex(this.grpResult, 0);
//              this.Controls.SetChildIndex(this.stbMain, 0);
            this.Controls.SetChildIndex(this.pnlBtnOKCancelHelpLayout, 0);
            this.pnlBtnOKCancelHelpLayout.ResumeLayout(false);
//              ((System.ComponentModel.ISupportInitialize)(this.stpInfo)).EndInit();
            this.stbMain.ResumeLayout(false);
            this.grpCriteria.ResumeLayout(false);
            this.grpCriteria.PerformLayout();
            this.pnlLocationKey.ResumeLayout(false);
            this.pnlLocationKey.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.FFindCriteriaDataTable)).EndInit();
            this.pnlPostCode.ResumeLayout(false);
            this.pnlPostCode.PerformLayout();
            this.pnlCity.ResumeLayout(false);
            this.pnlCity.PerformLayout();
            this.pnlAddr2.ResumeLayout(false);
            this.pnlAddr2.PerformLayout();
            this.pnlAddr3.ResumeLayout(false);
            this.pnlAddr3.PerformLayout();
            this.pnlAddr1.ResumeLayout(false);
            this.pnlAddr1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dsCriteria)).EndInit();
            this.grpResult.ResumeLayout(false);
            this.pnlBlankSearchResult.ResumeLayout(false);
            this.tlpAllCriteria.ResumeLayout(false);
            this.tlpAllCriteria.PerformLayout();
            this.tlpLeftCritera.ResumeLayout(false);
            this.tlpLeftCritera.PerformLayout();
            this.tlpRightCriteria.ResumeLayout(false);
            this.tlpRightCriteria.PerformLayout();
            this.pnlCounty.ResumeLayout(false);
            this.pnlCounty.PerformLayout();
            this.ResumeLayout(false);
        }

        private DevAge.Windows.Forms.Line lneCriteriaDivider;
        private System.Windows.Forms.Panel pnlCounty;
        private System.Windows.Forms.Panel pnlPostCode;
        private System.Windows.Forms.Panel pnlCity;
        private System.Windows.Forms.Panel pnlAddr2;
        private System.Windows.Forms.TableLayoutPanel tlpRightCriteria;
        private System.Windows.Forms.TableLayoutPanel tlpLeftCritera;
        private System.Windows.Forms.TableLayoutPanel tlpAllCriteria;
        private System.Windows.Forms.Button btnSearch;
        private System.Windows.Forms.Timer timerSearchResults;
        private TSgrdDataGridPaged grdResult;
        private System.Windows.Forms.Button btnClearCriteria;
        private System.Windows.Forms.GroupBox grpCriteria;
        private System.Windows.Forms.Panel pnlBlankSearchResult;
        private System.Windows.Forms.Panel pnlAddr1;
        private System.Windows.Forms.Label lblAddr1;
        private System.Windows.Forms.TextBox txtAddress1;
        private SplitButton critAddress1;
        private System.Windows.Forms.Panel pnlAddr3;
        private SplitButton critAddress3;
        private System.Windows.Forms.TextBox txtAddress3;
        private System.Windows.Forms.Label lblAddr3;
        private SplitButton critCounty;
        private System.Windows.Forms.TextBox txtCounty;
        private System.Windows.Forms.Label lblCounty;
        private SplitButton critAddress2;
        private System.Windows.Forms.TextBox txtAddress2;
        private System.Windows.Forms.Label lblStreet2;
        private SplitButton critCity;
        private System.Windows.Forms.TextBox txtCity;
        private System.Windows.Forms.Label lblCity;
        private SplitButton critPostCode;
        private System.Windows.Forms.TextBox txtPostCode;
        private System.Windows.Forms.Label lblPostCode;
        private System.Windows.Forms.Label lblCountry;
        private System.Data.DataSet dsCriteria;
        private System.Data.DataTable FFindCriteriaDataTable;
        private System.Data.DataColumn DataColumn1;
        private System.Data.DataColumn DataColumn2;
        private System.Data.DataColumn DataColumn3;
        private System.Data.DataColumn DataColumn4;
        private System.Data.DataColumn DataColumn5;
        private System.Data.DataColumn DataColumn6;
        private System.Data.DataColumn DataColumn7;
        private System.Data.DataColumn DataColumn8;
        private System.Data.DataColumn DataColumn9;
        private System.Data.DataColumn DataColumn10;
        private System.Data.DataColumn DataColumn11;
        private System.Data.DataColumn DataColumn12;
        private System.Data.DataColumn DataColumn13;
        private System.Data.DataColumn DataColumn14;
        private TUC_CountryComboBox cmbCountry;
        private System.Windows.Forms.Label lblSearchInfo;
        private System.Windows.Forms.Panel pnlLocationKey;
        private System.Windows.Forms.TextBox txtLocationKey;
        private System.Windows.Forms.Label lblLocationKey;
        private System.Windows.Forms.GroupBox grpResult;
        private Ict.Common.Controls.TExtStatusBarHelp stbMain;
        private System.Windows.Forms.Button btnOK;
        private System.Windows.Forms.Panel pnlBtnOKCancelHelpLayout;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnHelp;
    }
}