/*
 * This file is automatically generated, but can also be edited with the Designer
 */

using System;
using System.ComponentModel;
using System.Windows.Forms;

namespace Ict.Petra.Client.MPartner.Gui
{
    partial class TFindOptionsForm
    {
        /// <summary>
        /// Designer variable used to keep track of non-visual components.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Disposes resources used by the form.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null)
                {
                    components.Dispose();
                }
            }

            base.Dispose(disposing);
        }

        /// <summary>
        /// This method is required for Windows Forms designer support.
        /// Do not change the method contents inside the source code editor. The Forms designer might
        /// not be able to load this method if it was changed manually.
        /// </summary>
        private void InitializeComponent()
        {
#if TODO
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(TFindOptionsForm));
            this.clbPartnerFindCriteria = new System.Windows.Forms.CheckedListBox();
            this.ucoPartnerFindCriteriaSetup = new Ict.Petra.Client.MPartner.TUC_PartnerFindCriteria();
            this.btnMore = new System.Windows.Forms.Button();
            this.btnMoveUp = new System.Windows.Forms.Button();
            this.grpMoreOptions = new System.Windows.Forms.GroupBox();
            this.btnShowRightListItems = new System.Windows.Forms.Button();
            this.btnShowLeftListItems = new System.Windows.Forms.Button();
            this.btnMoveDown = new System.Windows.Forms.Button();
            this.btnMoveToLeftColumn = new System.Windows.Forms.Button();
            this.btnMoveToRightColumn = new System.Windows.Forms.Button();
            this.clbAddressFindCriteria = new System.Windows.Forms.CheckedListBox();
            this.clbOtherFindCriteria = new System.Windows.Forms.CheckedListBox();
            this.grpDisplayedSearchCriteria = new System.Windows.Forms.GroupBox();
            this.Label1 = new System.Windows.Forms.Label();
            this.Label2 = new System.Windows.Forms.Label();
            this.Label3 = new System.Windows.Forms.Label();
            this.chkShowMatchButtons = new System.Windows.Forms.CheckBox();
            this.chkExactPartnerKeyMatchSearch = new System.Windows.Forms.CheckBox();
            this.btnReset = new System.Windows.Forms.Button();
            this.btnFindCriteriaHelp = new System.Windows.Forms.Button();
            this.btnRearrangeCriteriaHelp = new System.Windows.Forms.Button();
            this.pnlBtnOKCancelHelpLayout.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.stpInfo)).BeginInit();
            this.grpMoreOptions.SuspendLayout();
            this.grpDisplayedSearchCriteria.SuspendLayout();
            this.SuspendLayout();

            //
            // btnOK
            //
            this.btnOK.Anchor =
                ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnOK.Location = new System.Drawing.Point(484, 5);
            this.btnOK.Size = new System.Drawing.Size(75, 23);
TODO: move statusbar texts to constructor
            this.sbtForm.SetStatusBarText(this.btnOK, "Accept data and continue");
            this.btnOK.Click += new System.EventHandler(this.BtnOK_Click);

            //
            // pnlBtnOKCancelHelpLayout
            //
            this.pnlBtnOKCancelHelpLayout.Controls.Add(this.btnReset);
            this.pnlBtnOKCancelHelpLayout.Controls.Add(this.btnMore);
            this.pnlBtnOKCancelHelpLayout.Dock = System.Windows.Forms.DockStyle.None;
            this.pnlBtnOKCancelHelpLayout.Location = new System.Drawing.Point(0, 223);
            this.pnlBtnOKCancelHelpLayout.Size = new System.Drawing.Size(650, 32);
            this.pnlBtnOKCancelHelpLayout.Controls.SetChildIndex(this.btnCancel, 0);
            this.pnlBtnOKCancelHelpLayout.Controls.SetChildIndex(this.btnHelp, 0);
            this.pnlBtnOKCancelHelpLayout.Controls.SetChildIndex(this.btnOK, 0);
            this.pnlBtnOKCancelHelpLayout.Controls.SetChildIndex(this.btnMore, 0);
            this.pnlBtnOKCancelHelpLayout.Controls.SetChildIndex(this.btnReset, 0);

            //
            // btnCancel
            //
            this.btnCancel.Anchor =
                ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnCancel.Location = new System.Drawing.Point(566, 5);
            this.btnCancel.Size = new System.Drawing.Size(75, 23);
            this.sbtForm.SetStatusBarText(this.btnCancel, "Cancel data entry and close");
            this.btnCancel.Click += new System.EventHandler(this.BtnCancel_Click);

            //
            // btnHelp
            //
            this.btnHelp.Anchor =
                ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.btnHelp.Location = new System.Drawing.Point(369, 4);
            this.btnHelp.Size = new System.Drawing.Size(75, 23);
            this.sbtForm.SetStatusBarText(this.btnHelp, "Help");
            this.btnHelp.Visible = false;

            //
            // stbMain
            //
            this.stbMain.Location = new System.Drawing.Point(0, 567);
            this.stbMain.Size = new System.Drawing.Size(650, 22);

            //
            // stpInfo
            //
            this.stpInfo.Width = 650;

            //
            // clbPartnerFindCriteria
            //
            this.clbPartnerFindCriteria.CheckOnClick = true;
            this.clbPartnerFindCriteria.Location = new System.Drawing.Point(28, 34);
            this.clbPartnerFindCriteria.Name = "clbPartnerFindCriteria";
            this.clbPartnerFindCriteria.Size = new System.Drawing.Size(174, 132);
            this.clbPartnerFindCriteria.TabIndex = 1;
            this.clbPartnerFindCriteria.ItemCheck += new System.Windows.Forms.ItemCheckEventHandler(this.ClbPartnerFindCriteria_ItemCheck);

            //
            // ucoPartnerFindCriteriaSetup
            //
            this.ucoPartnerFindCriteriaSetup.AutoScroll = true;
            this.ucoPartnerFindCriteriaSetup.AutoSize = true;
            this.ucoPartnerFindCriteriaSetup.BackColor = System.Drawing.SystemColors.ScrollBar;
            this.ucoPartnerFindCriteriaSetup.CriteriaFieldsLeft = null;
            this.ucoPartnerFindCriteriaSetup.CriteriaFieldsRight = null;
            this.ucoPartnerFindCriteriaSetup.CriteriaSetupMode = false;
            this.ucoPartnerFindCriteriaSetup.Font = new System.Drawing.Font("Verdana",
                8.25F,
                System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point,
                ((byte)(0)));
            this.ucoPartnerFindCriteriaSetup.Location = new System.Drawing.Point(8, 18);
            this.ucoPartnerFindCriteriaSetup.MainDS = null;
            this.ucoPartnerFindCriteriaSetup.Name = "ucoPartnerFindCriteriaSetup";
            this.ucoPartnerFindCriteriaSetup.RestrictedPartnerClass = null;
            this.ucoPartnerFindCriteriaSetup.Size = new System.Drawing.Size(616, 234);
            this.ucoPartnerFindCriteriaSetup.TabIndex = 5;
            this.ucoPartnerFindCriteriaSetup.TabStop = false;
            this.ucoPartnerFindCriteriaSetup.VerificationResultCollection = null;

            //
            // btnMore
            //
            this.btnMore.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.btnMore.Location = new System.Drawing.Point(7, 4);
            this.btnMore.Name = "btnMore";
            this.btnMore.Size = new System.Drawing.Size(75, 23);
            this.btnMore.TabIndex = 1;
            this.btnMore.Text = "&More >>";
            this.btnMore.Click += new System.EventHandler(this.BtnMore_Click);

            //
            // btnMoveUp
            //
            this.btnMoveUp.Enabled = false;
            this.btnMoveUp.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.btnMoveUp.Location = new System.Drawing.Point(106, 263);
            this.btnMoveUp.Name = "btnMoveUp";
            this.btnMoveUp.Size = new System.Drawing.Size(102, 23);
            this.btnMoveUp.TabIndex = 0;
            this.btnMoveUp.Text = "Move &Up";
            this.btnMoveUp.Click += new System.EventHandler(this.BtnMoveUp_Click);

            //
            // grpMoreOptions
            //
            this.grpMoreOptions.Controls.Add(this.btnRearrangeCriteriaHelp);
            this.grpMoreOptions.Controls.Add(this.btnShowRightListItems);
            this.grpMoreOptions.Controls.Add(this.btnShowLeftListItems);
            this.grpMoreOptions.Controls.Add(this.btnMoveDown);
            this.grpMoreOptions.Controls.Add(this.btnMoveUp);
            this.grpMoreOptions.Controls.Add(this.btnMoveToLeftColumn);
            this.grpMoreOptions.Controls.Add(this.btnMoveToRightColumn);
            this.grpMoreOptions.Controls.Add(this.ucoPartnerFindCriteriaSetup);
            this.grpMoreOptions.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.grpMoreOptions.Location = new System.Drawing.Point(7, 261);
            this.grpMoreOptions.Name = "grpMoreOptions";
            this.grpMoreOptions.Size = new System.Drawing.Size(634, 300);
            this.grpMoreOptions.TabIndex = 4;
            this.grpMoreOptions.TabStop = false;
            this.grpMoreOptions.Text = "Rearrange Find Criteria";

            //
            // btnShowRightListItems
            //
            this.btnShowRightListItems.BackColor = System.Drawing.Color.LightSalmon;
            this.btnShowRightListItems.Location = new System.Drawing.Point(538, 263);
            this.btnShowRightListItems.Name = "btnShowRightListItems";
            this.btnShowRightListItems.Size = new System.Drawing.Size(86, 23);
            this.btnShowRightListItems.TabIndex = 6;
            this.btnShowRightListItems.Text = "R.List Items";
            this.btnShowRightListItems.UseVisualStyleBackColor = false;
            this.btnShowRightListItems.Click += new System.EventHandler(this.BtnShowRightListItems_Click);

            //
            // btnShowLeftListItems
            //
            this.btnShowLeftListItems.BackColor = System.Drawing.Color.LightSalmon;
            this.btnShowLeftListItems.Location = new System.Drawing.Point(8, 265);
            this.btnShowLeftListItems.Name = "btnShowLeftListItems";
            this.btnShowLeftListItems.Size = new System.Drawing.Size(86, 23);
            this.btnShowLeftListItems.TabIndex = 6;
            this.btnShowLeftListItems.Text = "L.List Items";
            this.btnShowLeftListItems.UseVisualStyleBackColor = false;
            this.btnShowLeftListItems.Click += new System.EventHandler(this.BtnShowLeftListItems_Click);

            //
            // btnMoveDown
            //
            this.btnMoveDown.Enabled = false;
            this.btnMoveDown.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.btnMoveDown.Location = new System.Drawing.Point(210, 263);
            this.btnMoveDown.Name = "btnMoveDown";
            this.btnMoveDown.Size = new System.Drawing.Size(102, 23);
            this.btnMoveDown.TabIndex = 1;
            this.btnMoveDown.Text = "Move &Down";
            this.btnMoveDown.Click += new System.EventHandler(this.BtnMoveDown_Click);

            //
            // btnMoveToLeftColumn
            //
            this.btnMoveToLeftColumn.Enabled = false;
            this.btnMoveToLeftColumn.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.btnMoveToLeftColumn.Location = new System.Drawing.Point(324, 263);
            this.btnMoveToLeftColumn.Name = "btnMoveToLeftColumn";
            this.btnMoveToLeftColumn.Size = new System.Drawing.Size(102, 23);
            this.btnMoveToLeftColumn.TabIndex = 3;
            this.btnMoveToLeftColumn.Text = "Move To &Left";
            this.btnMoveToLeftColumn.Click += new System.EventHandler(this.BtnMoveToLeftColumn_Click);

            //
            // btnMoveToRightColumn
            //
            this.btnMoveToRightColumn.Enabled = false;
            this.btnMoveToRightColumn.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.btnMoveToRightColumn.Location = new System.Drawing.Point(428, 263);
            this.btnMoveToRightColumn.Name = "btnMoveToRightColumn";
            this.btnMoveToRightColumn.Size = new System.Drawing.Size(102, 23);
            this.btnMoveToRightColumn.TabIndex = 2;
            this.btnMoveToRightColumn.Text = "Move To &Right";
            this.btnMoveToRightColumn.Click += new System.EventHandler(this.BtnMoveToRightColumn_Click);

            //
            // clbAddressFindCriteria
            //
            this.clbAddressFindCriteria.CheckOnClick = true;
            this.clbAddressFindCriteria.Location = new System.Drawing.Point(230, 34);
            this.clbAddressFindCriteria.Name = "clbAddressFindCriteria";
            this.clbAddressFindCriteria.Size = new System.Drawing.Size(174, 132);
            this.clbAddressFindCriteria.TabIndex = 3;
            this.clbAddressFindCriteria.ItemCheck += new System.Windows.Forms.ItemCheckEventHandler(this.ClbAddressFindCriteria_ItemCheck);

            //
            // clbOtherFindCriteria
            //
            this.clbOtherFindCriteria.CheckOnClick = true;
            this.clbOtherFindCriteria.Location = new System.Drawing.Point(430, 36);
            this.clbOtherFindCriteria.Name = "clbOtherFindCriteria";
            this.clbOtherFindCriteria.Size = new System.Drawing.Size(174, 132);
            this.clbOtherFindCriteria.TabIndex = 5;
            this.clbOtherFindCriteria.Visible = false;
            this.clbOtherFindCriteria.ItemCheck += new System.Windows.Forms.ItemCheckEventHandler(this.ClbOtherFindCriteria_ItemCheck);

            //
            // grpDisplayedSearchCriteria
            //
            this.grpDisplayedSearchCriteria.Controls.Add(this.btnFindCriteriaHelp);
            this.grpDisplayedSearchCriteria.Controls.Add(this.clbPartnerFindCriteria);
            this.grpDisplayedSearchCriteria.Controls.Add(this.Label1);
            this.grpDisplayedSearchCriteria.Controls.Add(this.clbAddressFindCriteria);
            this.grpDisplayedSearchCriteria.Controls.Add(this.Label2);
            this.grpDisplayedSearchCriteria.Controls.Add(this.clbOtherFindCriteria);
            this.grpDisplayedSearchCriteria.Controls.Add(this.Label3);
            this.grpDisplayedSearchCriteria.Controls.Add(this.chkShowMatchButtons);
            this.grpDisplayedSearchCriteria.Controls.Add(this.chkExactPartnerKeyMatchSearch);
            this.grpDisplayedSearchCriteria.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.grpDisplayedSearchCriteria.Font = new System.Drawing.Font("Verdana",
                8.25F,
                System.Drawing.FontStyle.Regular,
                System.Drawing.GraphicsUnit.Point,
                ((byte)(0)));
            this.grpDisplayedSearchCriteria.Location = new System.Drawing.Point(7, 9);
            this.grpDisplayedSearchCriteria.Name = "grpDisplayedSearchCriteria";
            this.grpDisplayedSearchCriteria.Size = new System.Drawing.Size(634, 212);
            this.grpDisplayedSearchCriteria.TabIndex = 0;
            this.grpDisplayedSearchCriteria.TabStop = false;
            this.grpDisplayedSearchCriteria.Text = "Displayed Find Criteria";

            //
            // Label1
            //
            this.Label1.Location = new System.Drawing.Point(26, 18);
            this.Label1.Name = "Label1";
            this.Label1.Size = new System.Drawing.Size(172, 23);
            this.Label1.TabIndex = 0;
            this.Label1.Text = "&Partner Find Criteria:";

            //
            // Label2
            //
            this.Label2.Location = new System.Drawing.Point(230, 18);
            this.Label2.Name = "Label2";
            this.Label2.Size = new System.Drawing.Size(172, 23);
            this.Label2.TabIndex = 2;
            this.Label2.Text = "&Address Find Criteria:";

            //
            // Label3
            //
            this.Label3.Location = new System.Drawing.Point(428, 20);
            this.Label3.Name = "Label3";
            this.Label3.Size = new System.Drawing.Size(172, 23);
            this.Label3.TabIndex = 4;
            this.Label3.Text = "O&ther Find Criteria:";
            this.Label3.Visible = false;

            //
            // chkShowMatchButtons
            //
            this.chkShowMatchButtons.Location = new System.Drawing.Point(28, 188);
            this.chkShowMatchButtons.Name = "chkShowMatchButtons";
            this.chkShowMatchButtons.Size = new System.Drawing.Size(180, 18);
            this.chkShowMatchButtons.TabIndex = 6;
            this.chkShowMatchButtons.Text = "Sho&w \'Matching Pattern\' buttons";
            this.chkShowMatchButtons.CheckedChanged += new System.EventHandler(this.ChkHideMatchButtons_CheckedChanged);

            //
            // chkExactPartnerKeyMatchSearch
            //
            this.chkExactPartnerKeyMatchSearch.Location = new System.Drawing.Point(28, 168);
            this.chkExactPartnerKeyMatchSearch.Name = "chkExactPartnerKeyMatchSearch";
            this.chkExactPartnerKeyMatchSearch.Size = new System.Drawing.Size(180, 18);
            this.chkExactPartnerKeyMatchSearch.TabIndex = 5;
            this.chkExactPartnerKeyMatchSearch.Text = "Exact Partner &Key Match";

            //
            // btnReset
            //
            this.btnReset.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.btnReset.Location = new System.Drawing.Point(180, 4);
            this.btnReset.Name = "btnReset";
            this.btnReset.Size = new System.Drawing.Size(75, 23);
            this.sbtForm.SetStatusBarText(this.btnReset, "Reset Find Criteria to OpenPetra default");
            this.btnReset.TabIndex = 2;
            this.btnReset.Text = "&Reset";
            this.btnReset.Click += new System.EventHandler(this.BtnReset_Click);

            //
            // btnFindCriteriaHelp
            //
            this.btnFindCriteriaHelp.Anchor =
                ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnFindCriteriaHelp.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btnFindCriteriaHelp.Image = ((System.Drawing.Image)(resources.GetObject("btnFindCriteriaHelp.Image")));
            this.btnFindCriteriaHelp.Location = new System.Drawing.Point(604, 187);
            this.btnFindCriteriaHelp.Name = "btnFindCriteriaHelp";
            this.btnFindCriteriaHelp.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.btnFindCriteriaHelp.Size = new System.Drawing.Size(20, 19);
            this.btnFindCriteriaHelp.TabIndex = 7;
            this.btnFindCriteriaHelp.Click += new System.EventHandler(this.BtnFindCriteriaHelpClick);

            //
            // btnRearrangeCriteriaHelp
            //
            this.btnRearrangeCriteriaHelp.Anchor =
                ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnRearrangeCriteriaHelp.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btnRearrangeCriteriaHelp.Image = ((System.Drawing.Image)(resources.GetObject("btnRearrangeCriteriaHelp.Image")));
            this.btnRearrangeCriteriaHelp.Location = new System.Drawing.Point(604, 265);
            this.btnRearrangeCriteriaHelp.Name = "btnRearrangeCriteriaHelp";
            this.btnRearrangeCriteriaHelp.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.btnRearrangeCriteriaHelp.Size = new System.Drawing.Size(20, 19);
            this.btnRearrangeCriteriaHelp.TabIndex = 7;
            this.btnRearrangeCriteriaHelp.Click += new System.EventHandler(this.BtnRearrangeCriteriaHelpClick);

            //
            // TFindOptionsForm
            //
            this.AccessibleDescription = "";
            this.AutoScaleBaseSize = new System.Drawing.Size(6, 14);
            this.ClientSize = new System.Drawing.Size(650, 589);
            this.Controls.Add(this.grpDisplayedSearchCriteria);
            this.Controls.Add(this.grpMoreOptions);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "TFindOptionsForm";
            this.Text = "Find Options";
            this.Load += new System.EventHandler(this.TFindOptionsForm_Load);
            this.Closing += new System.ComponentModel.CancelEventHandler(this.TFindOptionsForm_Closing);
            this.Controls.SetChildIndex(this.grpMoreOptions, 0);
            this.Controls.SetChildIndex(this.stbMain, 0);
            this.Controls.SetChildIndex(this.pnlBtnOKCancelHelpLayout, 0);
            this.Controls.SetChildIndex(this.grpDisplayedSearchCriteria, 0);
            this.pnlBtnOKCancelHelpLayout.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.stpInfo)).EndInit();
            this.grpMoreOptions.ResumeLayout(false);
            this.grpMoreOptions.PerformLayout();
            this.grpDisplayedSearchCriteria.ResumeLayout(false);
            this.ResumeLayout(false);
#endif
        }

#if TODO
        private System.Windows.Forms.Button btnFindCriteriaHelp;
        private System.Windows.Forms.Button btnRearrangeCriteriaHelp;
        private System.Windows.Forms.Button btnReset;

        private System.Windows.Forms.CheckedListBox clbPartnerFindCriteria;
        private TUC_PartnerFindCriteria ucoPartnerFindCriteriaSetup;
        private System.Windows.Forms.Button btnMore;
        private System.Windows.Forms.Button btnMoveUp;
        private System.Windows.Forms.CheckedListBox clbAddressFindCriteria;
        private System.Windows.Forms.CheckedListBox clbOtherFindCriteria;
        private System.Windows.Forms.GroupBox grpMoreOptions;
        private System.Windows.Forms.Button btnMoveToRightColumn;
        private System.Windows.Forms.Button btnMoveToLeftColumn;
        private System.Windows.Forms.Button btnMoveDown;
        private System.Windows.Forms.GroupBox grpDisplayedSearchCriteria;

        /// <summary>XPBalloonTip1: SteepValley.Windows.Forms.XPBalloonTip;</summary>
        private System.Windows.Forms.Label Label1;
        private System.Windows.Forms.Label Label2;
        private System.Windows.Forms.Label Label3;
        private System.Windows.Forms.Button btnShowLeftListItems;
        private System.Windows.Forms.Button btnShowRightListItems;
        private System.Windows.Forms.CheckBox chkShowMatchButtons;
        private System.Windows.Forms.CheckBox chkExactPartnerKeyMatchSearch;
#endif
    }
}